### ISSUE TITLE
Bug in MasterPlaylist constructor?

### ISSUE THREAD

**Issue by ketankhairnar** [iheartradio/open-m3u8#23]
Please checkout below 2 lines from the constructor of com.iheartradio.m3u8.data.MasterPlaylist.    
    mPlaylists = playlists == null ? Collections.<PlaylistData>emptyList() : Collections.unmodifiableList(playlists);
    mIFramePlaylists = **playlists == null** ? Collections.<IFrameStreamInfo>emptyList() : Collections.unmodifiableList(iFramePlaylists);

If one forgets to add IFrameStreamInfo list while creating MasterPlaylist. It throws runtime NPE

**Comment by Wopple** [comment]
Thanks @ketankhairnar !

I will create a fix shortly.

**Comment by Wopple** [comment]
I have released 0.2.1 with the fix to maven central. It may be a couple hours before it becomes publicly available.

**Comment by ketankhairnar** [comment]
:+1:
