### ISSUE TITLE
No support for playlists in progress. 

### ISSUE THREAD

**Issue by dbousamra** [iheartradio/open-m3u8#26]
When writing a playlist, EXT-X-ENDLIST tag is always appended at the end. In progress playlists can have files appended as they become available.

**Comment by Wopple** [comment]
Can you explain what you mean by "in progress playlists?" What is an example API you are looking for?

**Comment by dbousamra** [comment]
I don't yet have an API in mind. I was just reading the [Apple](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html#//apple_ref/doc/uid/TP40008332-CH102-SW12) docs and saw some info about the #EXT-X-ENDLIST tag, and how there are playlists that are still valid with an omitted tag. At the moment, I just string trim the completed playlist of the tag, because looking at the source, I couldn't see any logic around ENDLIST tags.

**Comment by Wopple** [comment]
Within the streaming domain, my guess is that there are two use cases here and you are interested in the second:

1. Make periodic short lived requests for a few chunks at a time and concatenate them on the client
2. Make one long lived request that the server keeps open and periodically appends tracks as they become available

This library only supports the 1st one at present. To support the second, we would have to provide an event based API.

Are my assumptions correct?
