### ISSUE TITLE
Bypass unsupported Tag Exceptions through config if implementation pending

### ISSUE THREAD

**Issue by ketankhairnar** [iheartradio/open-m3u8#27]
I came across situation where one of the m3u8 had tag EXT-X-PROGRAM-DATE-TIME which is part of spec [https://tools.ietf.org/html/draft-pantos-http-live-streaming-16#section-4.3.2.6]

Since library is not complete it ends up throwing exception.  Adding parsing for all such tags is going to take a while. Till then is there better alternative than throwing  exception?

Can one bypass that [through config maybe]? Can you help with example of LENIENT mode.

Here us sample m3u8 which fails to parse 

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:11
#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z
#EXTINF:10.010010,no-desc
Fragments(video=0,format=m3u8-aapl-v3,audiotrack=aac_UND_2_127)
#EXTINF:10.010010,no-desc
Fragments(video=100100100,format=m3u8-aapl-v3,audiotrack=aac_UND_2_127)
#EXTINF:10.010010,no-desc
Fragments(video=200200200,format=m3u8-aapl-v3,audiotrack=aac_UND_2_127)
#EXTINF:10.010010,no-desc
Fragments(video=300300300,format=m3u8-aapl-v3,audiotrack=aac_UND_2_127)
```

**Comment by ketankhairnar** [comment]
Ok. Got the LENIENT mode. RTFM :)

**Comment by Wopple** [comment]
:thumbsup:
