### ISSUE TITLE
EXT-X-PROGRAM-DATE-TIME support integration

### ISSUE THREAD

**Issue by kalemeister** [iheartradio/open-m3u8#29]
Hi.
I used this library for a small application I made. The m3u8 files I was downloading had the "ext-x-program-date-time" tag. I added some code so that open-m3u8 supports the tag in strict parsing mode.
I'm not sure how to commit it though. I've never used github. I couldn't find any option to make a new branch or anything. So would anyone help guiding on what I should do next?

**Comment by Wopple** [comment]
- fork this repo in github
- clone your repo on your local machine
- apply your changes to your local repo
- commit and push your changes to any branch in your remote repo (doesn't have to be master)
- submit a pull request from your repo's branch to this repo's master branch in github

For more help: https://help.github.com/articles/creating-a-pull-request/

**Comment by kalemeister** [comment]
Okay, thank you, Wopple. I've created a fork, did my updates, and created a pull request.
You can close this.
